site_name: Buildcraft-Additions
repo_url: https://github.com/ModDocs/bca
strict: true

markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - Home: index.md
  - Blocks: 
    - Multiblocks: Blocks/Multiblocks.md
